# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: esp_local_ctrl.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code for ESP local control."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

from . import constants_pb2 as constants__pb2

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    "",
    "esp_local_ctrl.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x14\x65sp_local_ctrl.proto\x1a\x0f\x63onstants.proto\"\x15\n\x13"
    b"\x43mdGetPropertyCount\">\n\x14RespGetPropertyCount\x12\x17\n\x06status"
    b"\x18\x01 \x01(\x0e\x32\x07.Status\x12\r\n\x05\x63ount\x18\x02 \x01(\r\"a\n"
    b"\x0cPropertyInfo\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12"
    b"\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\r\n\x05"
    b"\x66lags\x18\x04 \x01(\r\x12\r\n\x05value\x18\x05 \x01(\x0c\"'\n\x14"
    b"\x43mdGetPropertyValues\x12\x0f\n\x07indices\x18\x01 \x03(\r\"N\n\x15"
    b"RespGetPropertyValues\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status"
    b"\x12\x1c\n\x05props\x18\x02 \x03(\x0b\x32\r.PropertyInfo\"-\n\rPropertyValue"
    b"\x12\r\n\x05index\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x0c\"5\n\x14"
    b"\x43mdSetPropertyValues\x12\x1d\n\x05props\x18\x01 \x03(\x0b\x32\x0e"
    b".PropertyValue\"0\n\x15RespSetPropertyValues\x12\x17\n\x06status\x18\x01 "
    b"\x01(\x0e\x32\x07.Status\"5\n\x14ReportPropertyValues\x12\x1d\n\x05props"
    b"\x18\x01 \x03(\x0b\x32\x0e.PropertyValue\"\xae\x03\n\x10LocalCtrlMessage"
    b"\x12\x1e\n\x03msg\x18\x01 \x01(\x0e\x32\x11.LocalCtrlMsgType\x12\x32\n\x12"
    b"\x63md_get_prop_count\x18\n \x01(\x0b\x32\x14.CmdGetPropertyCountH\x00\x12"
    b"\x34\n\x13resp_get_prop_count\x18\x0b \x01(\x0b\x32\x15.RespGetPropertyCount"
    b"H\x00\x12\x32\n\x11\x63md_get_prop_vals\x18\x0c \x01(\x0b\x32\x15"
    b".CmdGetPropertyValuesH\x00\x12\x34\n\x12resp_get_prop_vals\x18\r \x01(\x0b"
    b"\x32\x16.RespGetPropertyValuesH\x00\x12\x32\n\x11\x63md_set_prop_vals\x18"
    b"\x0e \x01(\x0b\x32\x15.CmdSetPropertyValuesH\x00\x12\x34\n\x12resp_set_prop_vals"
    b"\x18\x0f \x01(\x0b\x32\x16.RespSetPropertyValuesH\x00\x12\x31\n\x10"
    b"report_prop_vals\x18\x10 \x01(\x0b\x32\x15.ReportPropertyValuesH\x00\x42\t\n"
    b"\x07payload*\xe5\x01\n\x10LocalCtrlMsgType\x12\x1b\n\x17TypeCmdGetPropertyCount"
    b"\x10\x00\x12\x1c\n\x18TypeRespGetPropertyCount\x10\x01\x12\x1c\n\x18"
    b"TypeCmdGetPropertyValues\x10\x04\x12\x1d\n\x19TypeRespGetPropertyValues"
    b"\x10\x05\x12\x1c\n\x18TypeCmdSetPropertyValues\x10\x06\x12\x1d\n\x19"
    b"TypeRespSetPropertyValues\x10\x07\x12\x1c\n\x18TypeReportPropertyValues"
    b"\x10\x08\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "esp_local_ctrl_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LOCALCTRLMSGTYPE"]._serialized_start = 989
    _globals["_LOCALCTRLMSGTYPE"]._serialized_end = 1218
    _globals["_CMDGETPROPERTYCOUNT"]._serialized_start = 41
    _globals["_CMDGETPROPERTYCOUNT"]._serialized_end = 62
    _globals["_RESPGETPROPERTYCOUNT"]._serialized_start = 64
    _globals["_RESPGETPROPERTYCOUNT"]._serialized_end = 126
    _globals["_PROPERTYINFO"]._serialized_start = 128
    _globals["_PROPERTYINFO"]._serialized_end = 225
    _globals["_CMDGETPROPERTYVALUES"]._serialized_start = 227
    _globals["_CMDGETPROPERTYVALUES"]._serialized_end = 266
    _globals["_RESPGETPROPERTYVALUES"]._serialized_start = 268
    _globals["_RESPGETPROPERTYVALUES"]._serialized_end = 346
    _globals["_PROPERTYVALUE"]._serialized_start = 348
    _globals["_PROPERTYVALUE"]._serialized_end = 393
    _globals["_CMDSETPROPERTYVALUES"]._serialized_start = 395
    _globals["_CMDSETPROPERTYVALUES"]._serialized_end = 448
    _globals["_RESPSETPROPERTYVALUES"]._serialized_start = 450
    _globals["_RESPSETPROPERTYVALUES"]._serialized_end = 498
    _globals["_REPORTPROPERTYVALUES"]._serialized_start = 500
    _globals["_REPORTPROPERTYVALUES"]._serialized_end = 553
    _globals["_LOCALCTRLMESSAGE"]._serialized_start = 556
    _globals["_LOCALCTRLMESSAGE"]._serialized_end = 986
# @@protoc_insertion_point(module_scope)
