# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sec0.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code for security0."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

from . import constants_pb2 as constants__pb2

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    "",
    "sec0.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\nsec0.proto\x1a\x0f\x63onstants.proto\"\x0e\n\x0cS0SessionCmd\"(\n\r"
    b"S0SessionResp\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"n\n\x0b"
    b"Sec0Payload\x12\x19\n\x03msg\x18\x01 \x01(\x0e\x32\x0c.Sec0MsgType\x12\x1b"
    b"\n\x02sc\x18\x14 \x01(\x0b\x32\r.S0SessionCmdH\x00\x12\x1c\n\x02sr\x18\x15 "
    b"\x01(\x0b\x32\x0e.S0SessionRespH\x00\x42\t\n\x07payload*>\n\x0bSec0MsgType"
    b"\x12\x16\n\x12S0_Session_Command\x10\x00\x12\x17\n\x13S0_Session_Response"
    b"\x10\x01\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sec0_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SEC0MSGTYPE"]._serialized_start = 201
    _globals["_SEC0MSGTYPE"]._serialized_end = 263
    _globals["_S0SESSIONCMD"]._serialized_start = 31
    _globals["_S0SESSIONCMD"]._serialized_end = 45
    _globals["_S0SESSIONRESP"]._serialized_start = 47
    _globals["_S0SESSIONRESP"]._serialized_end = 87
    _globals["_SEC0PAYLOAD"]._serialized_start = 89
    _globals["_SEC0PAYLOAD"]._serialized_end = 199
# @@protoc_insertion_point(module_scope)
